[project]
name = "vebee-ats"
version = "1.0.0"
description = "VeeBee ATS Resume Analysis Platform"
requires-python = "~=3.12.0"

dependencies = [
    "fastapi[standard]",
    "spacy",
    "python-multipart",
    "pypdf",
    "python-docx",
    "numpy",
    "pandas",
    "scikit-learn",
    "xgboost",
    "lightgbm",
    "joblib",
    "sentence-transformers",
    "pymongo",
    "python-dotenv",
    "scipy",
]

[tool.vercel]
entrypoint = "backend.app.main:app"
